### ISSUE TITLE
データ更新エラーを修正

### ISSUE THREAD

**Issue by nisshi-dev** [nishidayoshikatsu/covid19-yamaguchi-opendata#57]
## 発生している問題

- 以下のエラーが発生していることを確認している
> Traceback (most recent call last):
  File "main.py", line 11, in <module>
    dm.validate()
  File "/root/dataloader.py", line 122, in validate
    jsonschema.validate(self.data[key], self.SCHEMAS[key])
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: '入院' is a required property

> Failed validating 'required' in schema['properties']['data']['items']:
    {'default': {},
     'properties': {'入院': {'default': '', 'type': 'integer'},
                    '全国地方公共団体コード': {'default': '', 'type': 'string'},
                    '受付_年月日': {'default': '', 'type': 'string'},
                    '市区町村名': {'default': '', 'type': 'string'},
                    '死亡': {'default': '', 'type': 'integer'},
                    '退院': {'default': '', 'type': 'integer'},
                    '都道府県名 ': {'default': '', 'type': 'string'}},
     'required': ['受付_年月日', '入院', '退院', '死亡'],
     'type': 'object'}

> On instance['data'][0]:
    {' 市区町村名 ': '',
     ' 都道府県名': '山口県',
     '入院等': '15',
     '全国地方公共団体コード': '350001',
     '受付_年月日': '2020/4/15',
     '死亡': 0,
     '退院': 5}
make: *** [exec] Error 1

**Comment by nisshi-dev** [comment]
上記のエラー解決後
> Traceback (most recent call last):
  File "main.py", line 17, in <module>
    gd.main()
  File "/root/dataloader.py", line 160, in main
    self.generate_patients_cnt()
  File "/root/dataloader.py", line 180, in generate_patients_cnt
    prev_data = self.add_patiennts_data(prev_data, data)
  File "/root/dataloader.py", line 484, in add_patiennts_data
    daily_cnt = self.daily_patients(data["data"])
  File "/root/dataloader.py", line 512, in daily_patients
    dt = self.format_date(date_str)
  File "/root/dataloader.py", line 447, in format_date
    date_dt = datetime.datetime.strptime(date_str, "%Y/%m/%d")
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2021/' does not match format '%Y/%m/%d'
make: *** [exec] Error 1
